version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
    ports:
      - "5432:5432"
  axon-server:
    image: axoniq/axonserver:latest
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      axoniq_axonserver_hostname: axon-server
      axoniq_axonserver_autocluster_first: axon-server
      axoniq_axonserver_autocluster_contexts: _admin,default
    volumes:
      - data:/axonserver/data
      - events:/axonserver/events

volumes:
  data:
    driver: local
  events:
    driver: local